name: Workers Stats

on:
  schedule:
    - cron: "0 23 * * *"   # 每天 UTC+1 执行
  workflow_dispatch:

jobs:
  fetch-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Cloudflare Stats Script
        env:
          CF_ACCOUNT_IDS: ${{ secrets.CF_ACCOUNT_IDS }}
          CF_API_TOKENS: ${{ secrets.CF_API_TOKENS }}
          CF_USERNAMES: ${{ secrets.CF_USERNAMES }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_SPLIT_SEND: ${{ secrets.TELEGRAM_SPLIT_SEND }}
          DAYS: 2
        run: python cf_workers_stats.py
